/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criterioc;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.awt.Image;
import javax.swing.JOptionPane;
/**
 *
 * @author camey
 */
public class AsignarMedicamento extends javax.swing.JFrame {
    private static String basededatos = "criterio c";
    private static String contrasena = "infobi";
    private static String servidor = "localhost";
    private static String usuario = "root";
    private String rutaImagen = "";
    
    public static void asignarMedicamento(String usuarioNombre, String nombreMedicamento, java.util.Date fechaInicio, java.util.Date fechaFin) {
     ConeccionBD BD = null;
    try {
        BD = new ConeccionBD("jdbc:mysql://" + servidor + ":3306/" + basededatos + "?useSSL=false&characterEncoding=utf-8", usuario, contrasena);
        BD.getNewConnection();
        Statement st = BD.getCurrentConnection().createStatement();

        // Convertir fechas a formato SQL
        java.sql.Date sqlFechaInicio = new java.sql.Date(fechaInicio.getTime());
        java.sql.Date sqlFechaFin = new java.sql.Date(fechaFin.getTime());

        String query = "INSERT INTO asignacion_medicamento (Usuario_Nombre, Nombre_medicamento, Fecha_inicio, Fecha_final) VALUES ("
                     + "'" + usuarioNombre + "', "
                     + "'" + nombreMedicamento + "', "
                     + "'" + sqlFechaInicio + "', "
                     + "'" + sqlFechaFin + "')";
        st.executeUpdate(query);
        BD.closeConnection();
        JOptionPane.showMessageDialog(null, "¡Medicamento asignado correctamente!");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al asignar medicamento:\n" + e.getMessage());
    }
}
    
    private void cargarUsuarios() {
    cbx_usuario.removeAllItems();
    try {
        ConeccionBD BD = new ConeccionBD("jdbc:mysql://" + servidor + ":3306/" + basededatos + "?useSSL=false&characterEncoding=utf-8", usuario, contrasena);
        BD.getNewConnection();
        Statement st = BD.getCurrentConnection().createStatement();
        ResultSet rs = st.executeQuery("SELECT Nombre FROM usuario");

        while (rs.next()) {
            cbx_usuario.addItem(rs.getString("Nombre"));
        }

        BD.closeConnection();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar usuarios:\n" + e.getMessage());
    }
}

private void cargarMedicamentos() {
    cbx_medicamento.removeAllItems();
    try {
        ConeccionBD BD = new ConeccionBD("jdbc:mysql://" + servidor + ":3306/" + basededatos + "?useSSL=false&characterEncoding=utf-8", usuario, contrasena);
        BD.getNewConnection();
        Statement st = BD.getCurrentConnection().createStatement();
        ResultSet rs = st.executeQuery("SELECT Nombre_medicamento FROM medicamentos");

        while (rs.next()) {
            cbx_medicamento.addItem(rs.getString("Nombre_medicamento"));
        }

        BD.closeConnection();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar medicamentos:\n" + e.getMessage());
    }
}
    
    /**
     * Creates new form AsignarMedicamento
     */
    public AsignarMedicamento() {
        initComponents();
        btn_asignar.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_asignarActionPerformed(evt);
    }
    });
        cargarUsuarios();
        cargarMedicamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_medicamento = new javax.swing.JComboBox<>();
        lbl_tt = new javax.swing.JLabel();
        cbx_usuario = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lbl_fecha1 = new javax.swing.JLabel();
        lbl_fecha2 = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_medicamento = new javax.swing.JLabel();
        btn_asignar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_medicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_tt.setText("Asignar Medicamento");

        cbx_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_usuarioActionPerformed(evt);
            }
        });

        lbl_fecha1.setText("Fecha Inicio");

        lbl_fecha2.setText("Fecha Final");

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_usuario.setText("Usuario");

        lbl_medicamento.setText("Medicamento");

        btn_asignar.setText("asignar");
        btn_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignarActionPerformed(evt);
            }
        });

        jLabel1.setText("kl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_usuario)
                                        .addComponent(cbx_usuario, 0, 98, Short.MAX_VALUE)
                                        .addComponent(cbx_medicamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lbl_medicamento))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fecha2)
                                    .addComponent(lbl_fecha1)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_asignar)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tt)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuario)
                    .addComponent(lbl_fecha1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_medicamento)
                    .addComponent(lbl_fecha2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btn_asignar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_usuarioActionPerformed

    private void btn_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignarActionPerformed
        // TODO add your handling code here:
       try {
        String usuarioSeleccionado = (String) cbx_usuario.getSelectedItem();
        String medicamentoSeleccionado = (String) cbx_medicamento.getSelectedItem();
        java.util.Date fechaInicio = jDateChooser1.getDate();
        java.util.Date fechaFin = jDateChooser2.getDate();

        if (usuarioSeleccionado == null || medicamentoSeleccionado == null || fechaInicio == null || fechaFin == null) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }

        asignarMedicamento(usuarioSeleccionado, medicamentoSeleccionado, fechaInicio, fechaFin);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al asignar: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btn_asignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asignar;
    private javax.swing.JComboBox<String> cbx_medicamento;
    private javax.swing.JComboBox<String> cbx_usuario;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_fecha1;
    private javax.swing.JLabel lbl_fecha2;
    private javax.swing.JLabel lbl_medicamento;
    private javax.swing.JLabel lbl_tt;
    private javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
}
