/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criterioc;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.awt.Image;
import javax.swing.JOptionPane;
/**
 *
 * @author camey
 */
public class Cita_medica_agregar extends javax.swing.JFrame {
        
    private static String basededatos = "criterio c";
    private static String contrasena = "infobi";
    private static String servidor = "localhost";
    private static String usuario = "root";
    
    public static void insertar_metodo1 (String Numero_cita, String Fecha, String Hora, String Doctor, String Usuario_Nombre, String ruta_imagen)
    {
        ConeccionBD BD = null;
        try
        {
            BD = new ConeccionBD ("jdbc:mysql://"+servidor+":3306/"+basededatos+"?useSSL=false"
                                + "&characterEncoding=utf-8",usuario,contrasena);
            BD.getNewConnection();
            try
            {
                Statement stQueryInsert = BD.getCurrentConnection().createStatement();
                String queryInsert = "INSERT INTO cita_medica (Numero_cita, Fecha, Hora, Doctor, Usuario_Nombre, ruta_imagen) " +
                     "VALUES ('" + Numero_cita+ "','" + Fecha + "','" + Hora + "' , '"+ Doctor +"' , '"+ Usuario_Nombre +"' , '"+ ruta_imagen +"')";
                
                stQueryInsert.executeUpdate(queryInsert);
            } catch (Exception e1) {
                JOptionPane.showMessageDialog(null, "Error al insertar: " + e1.getMessage());
                e1.printStackTrace();
            } finally {
                BD.closeConnection();
            }
        } catch (Exception e0) {
            JOptionPane.showMessageDialog(null, "Error de conexión: " + e0.getMessage());
            e0.printStackTrace();
        }
    }
    
    
    /**
     * Creates new form Cita_medica_agregar
     */
    public Cita_medica_agregar() {
        initComponents();
        setLocationRelativeTo(null);
        this.dispose();
        

        setTitle("Agregar Cita Medica");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tt = new javax.swing.JLabel();
        lbl_medico = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        lbl_paciente = new javax.swing.JLabel();
        txt_cita = new javax.swing.JTextField();
        txt_medico = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        txt_hora = new javax.swing.JTextField();
        txt_paciente = new javax.swing.JTextField();
        lbl_foto = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_imagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tt.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_tt.setForeground(new java.awt.Color(0, 0, 102));
        lbl_tt.setText("Registra Cita Medica");

        lbl_medico.setText("Nombre del Medico:");

        lbl_fecha.setText("Fecha de la Cita:");

        lbl_hora.setText("Horario de la cita:");

        lbl_paciente.setText("Nombre paciente");

        lbl_foto.setText("Imagen");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_imagen.setText("Ingresar imagen");
        btn_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_medico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_tt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_hora)
                    .addComponent(txt_paciente)
                    .addComponent(txt_medico)
                    .addComponent(txt_cita, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_imagen)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tt)
                    .addComponent(txt_cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_medico)
                    .addComponent(txt_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fecha)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hora)
                    .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_paciente)
                    .addComponent(txt_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btn_guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_imagen)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try{
        String cita = txt_cita.getText().trim();
        String fecha = txt_fecha.getText().trim();
        String hora = txt_hora.getText().trim();
        String doctor = txt_medico.getText().trim();
        String paciente = txt_paciente.getText().trim();
        String ruta_imagen = lbl_foto.getIcon() != null ? ((ImageIcon) lbl_foto.getIcon()).getDescription() : "";
        
        String[] partesFecha = fecha.split("/"); //validacion de la fecha
        if (partesFecha.length != 3) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto, utilise d/M/y");
            return;
        }
        String fechaMySQL = partesFecha[2] + "-" + partesFecha[1] + "-" + partesFecha[0];
        
        insertar_metodo1(cita, fechaMySQL, hora, doctor, paciente, ruta_imagen);
        JOptionPane.showMessageDialog(this, "Cita guardada exitosamente");//para verificar que todo este bien
        Cita_medica mostrarCita = new Cita_medica();
            mostrarCita.mostrarDatos(cita, fecha, hora, doctor, paciente, ruta_imagen);
            mostrarCita.setVisible(true);
    } catch (Exception e) {
        
        
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
        
            
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imagenActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg"));
    
    // Abre el diálogo para seleccionar imagen
    int resultado = fileChooser.showOpenDialog(this);
    
    // selecciona una imagen
    if (resultado == JFileChooser.APPROVE_OPTION) {
        File archivoImagen = fileChooser.getSelectedFile();
        try {
            //  Carga la imagen 
            ImageIcon icono = new ImageIcon(archivoImagen.getAbsolutePath());
            Image imagen = icono.getImage().getScaledInstance(
                lbl_foto.getWidth(), 
                lbl_foto.getHeight(), 
                Image.SCALE_SMOOTH
            );
            //  Muestra la imagen en el lbl
            lbl_foto.setIcon(new ImageIcon(imagen));
            
            
            ((ImageIcon)lbl_foto.getIcon()).setDescription(archivoImagen.getAbsolutePath());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_btn_imagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cita_medica_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cita_medica_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cita_medica_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cita_medica_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cita_medica_agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_imagen;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_medico;
    private javax.swing.JLabel lbl_paciente;
    private javax.swing.JLabel lbl_tt;
    private javax.swing.JTextField txt_cita;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_hora;
    private javax.swing.JTextField txt_medico;
    private javax.swing.JTextField txt_paciente;
    // End of variables declaration//GEN-END:variables
}
