/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criterioc;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.awt.Image;
import javax.swing.JOptionPane;
/**
 *
 * @author camey
 */
public class Registro_Usuario extends javax.swing.JFrame {
    
            
    private static String basededatos = "criterio c";
    private static String contrasena = "infobi";
    private static String servidor = "localhost";
    private static String usuario = "root";
    
    
    public static void insertar_metodo1 (String Nombre, String Edad, String Peso, String Altura, String Correo, String ruta_imagen)
    {
        ConeccionBD BD = null;
        try
        {
            BD = new ConeccionBD ("jdbc:mysql://"+servidor+":3306/"+basededatos+"?useSSL=false"
                                + "&characterEncoding=utf-8",usuario,contrasena);
            BD.getNewConnection();

            try
            {
                Statement stQueryInsert = BD.getCurrentConnection().createStatement();
                String queryInsert = "INSERT INTO usuario (Nombre, Edad, Peso, Altura, Correo,ruta_imagen )\n" +
                                    "VALUES ('"+Nombre+"','"+Edad+"','"+Peso+"','"+Altura+"','"+Correo+"','"+ruta_imagen+"')";
                stQueryInsert.executeUpdate(queryInsert);
                BD.closeConnection();
            }
            catch (Exception e1)
            {
                e1.printStackTrace();
            }
        }
        catch (Exception e0)
        {
            e0.printStackTrace();
        }
    }


    /**
     * Creates new form Registro_Usuario
     */
    public Registro_Usuario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Registro Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tt = new javax.swing.JLabel();
        lbl_foto = new javax.swing.JLabel();
        lbl_tt2 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_peso = new javax.swing.JLabel();
        lbl_edad = new javax.swing.JLabel();
        lbl_altura = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_peso = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_altura = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        btn_imagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tt.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        lbl_tt.setForeground(new java.awt.Color(0, 0, 51));
        lbl_tt.setText("Registro Usuario");

        lbl_foto.setText("Imagen");

        lbl_tt2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_tt2.setText("Registro Datos");

        lbl_nombre.setText("Nombre:");

        lbl_peso.setText("Peso:");

        lbl_edad.setText("Edad:");

        lbl_altura.setText("Altura:");

        lbl_correo.setText("Correo electronico");

        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_imagen.setText("Ingresar Imagen");
        btn_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_tt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_imagen)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(75, 75, 75)
                                .addComponent(btn_ingresar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_correo)
                                .addGap(22, 22, 22)
                                .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_altura)
                                .addGap(77, 77, 77)
                                .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_edad)
                                .addGap(82, 82, 82)
                                .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_peso)
                                    .addComponent(lbl_tt2)
                                    .addComponent(lbl_nombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_imagen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_peso)
                            .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_edad)
                            .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_altura)
                            .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_correo)
                            .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(btn_ingresar))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:
        String nombre = txt_nombre.getText().trim();
        String edad = txt_edad.getText().trim();
        String peso = txt_peso.getText().trim();
        String altura = txt_altura.getText().trim();
        String correo = txt_correo.getText().trim();
        String ruta_imagen = lbl_foto.getIcon() != null ? ((ImageIcon) lbl_foto.getIcon()).getDescription() : "";
        insertar_metodo1(nombre,edad,peso,altura,correo,ruta_imagen);
        Usuario v = new Usuario(); 
        v.mostrarDatos(nombre, edad, peso, altura, correo, ruta_imagen);
                v.setVisible(true); 
        new Thread(() -> {
        boolean enviado = Correo.sendMedicationReminder(
            correo,
            txt_nombre.getText().trim(),
            "Registro Exitoso",
            "Ahora recibirás recordatorios",
            "Próxima notificación: " 
        );
        if (enviado) {
            System.out.println("Correo de confirmación enviado");
        }
    }).start();
        dispose();
        
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imagenActionPerformed
        // TODO add your handling code here:
                                                  
    
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg"));
    
    // Abre el diálogo para seleccionar imagen
    int resultado = fileChooser.showOpenDialog(this);
    
    // selecciona una imagen
    if (resultado == JFileChooser.APPROVE_OPTION) {
        File archivoImagen = fileChooser.getSelectedFile();
        try {
            //  Carga la imagen 
            ImageIcon icono = new ImageIcon(archivoImagen.getAbsolutePath());
            Image imagen = icono.getImage().getScaledInstance(
                lbl_foto.getWidth(), 
                lbl_foto.getHeight(), 
                Image.SCALE_SMOOTH
            );
            // Muestra la imagen en el lbl
            lbl_foto.setIcon(new ImageIcon(imagen));
            
            
            ((ImageIcon)lbl_foto.getIcon()).setDescription(archivoImagen.getAbsolutePath());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

        
    }//GEN-LAST:event_btn_imagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        recordatorio.startReminderService();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imagen;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_altura;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_edad;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_peso;
    private javax.swing.JLabel lbl_tt;
    private javax.swing.JLabel lbl_tt2;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_peso;
    // End of variables declaration//GEN-END:variables
}
