package criterioc;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.awt.Image;
import javax.swing.JOptionPane;
/**
 *
 * @author camey
 */
public class Registro_medicamento extends javax.swing.JFrame {
    private static String basededatos = "criterio c";
    private static String contrasena = "infobi";
    private static String servidor = "localhost";
    private static String usuario = "root";
    private String rutaImagen = "";
    
    private void limpiarCampos() {
    txt_nombre.setText("");
    txt_dosis.setText("");
    txt_horario.setText("");
    txt_paciente.setText("");
    txt_frecuencia.setText("");
    lbl_foto.setIcon(null);
    rutaImagen = "";
}
    
    public static void insertar_metodo1 (String Nombre_medicamento, String Hora, String Dosis, 
        String Usuario_nombre, String rutaImagen, int Frecuencia) {
    ConeccionBD BD = null;
    try {
        BD = new ConeccionBD ("jdbc:mysql://"+servidor+":3306/"+basededatos+"?useSSL=false"
                            + "&characterEncoding=utf-8",usuario,contrasena);
        BD.getNewConnection();
        Statement stQueryInsert = BD.getCurrentConnection().createStatement();
        String queryInsert = "INSERT INTO medicamentos (Nombre_medicamento, Hora, Dosis, Usuario_Nombre, "
                + "imagen, Frecuencia) " +
             "VALUES ('" + Nombre_medicamento + "','" + Hora + "','" + Dosis + "',"
                + "'" + Usuario_nombre + "','" + (rutaImagen != null ? rutaImagen : "") + "'," + Frecuencia + ")";
        stQueryInsert.executeUpdate(queryInsert);
        BD.closeConnection();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al insertar el medicamento:\n" + e.getMessage());
    }
}
    
    /**
     * Creates new form Registro_medicamento
     */
    public Registro_medicamento() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Registro Medicamento");
        

        btn_imagen.addActionListener(new java.awt.event.ActionListener() {
            
        public void actionPerformed(java.awt.event.ActionEvent evt) { //imagenes
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "jpg", "png", "jpeg");
        archivo.setFileFilter(filtro);
        int seleccion = archivo.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File imagenSeleccionada = archivo.getSelectedFile();
            rutaImagen = imagenSeleccionada.getAbsolutePath();

            ImageIcon icono = new ImageIcon(rutaImagen);
            Image imagenEscalada = icono.getImage().getScaledInstance(lbl_foto.getWidth(), 
                    lbl_foto.getHeight(), Image.SCALE_SMOOTH);
            lbl_foto.setIcon(new ImageIcon(imagenEscalada));
            }
        }
}); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tt = new javax.swing.JLabel();
        lbl_foto = new javax.swing.JLabel();
        btn_imagen = new javax.swing.JButton();
        lbl_tt2 = new javax.swing.JLabel();
        lbl_dosis = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        lbl_paciente = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        txt_paciente = new javax.swing.JTextField();
        txt_horario = new javax.swing.JTextField();
        txt_dosis = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        txt_frecuencia = new javax.swing.JTextField();
        lbl_frecuencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tt.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        lbl_tt.setText("Registro Medicamento");

        lbl_foto.setText("Imagen");

        btn_imagen.setText("Ingrese Imagen ");
        btn_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imagenActionPerformed(evt);
            }
        });

        lbl_tt2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_tt2.setText("Ingrese Datos");

        lbl_dosis.setText("Dosis:");

        lbl_hora.setText("Horario:");

        lbl_paciente.setText("Nombre Paciente:");

        lbl_nombre.setText("Nombre Medicamento:");

        txt_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_horarioActionPerformed(evt);
            }
        });

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        txt_frecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_frecuenciaActionPerformed(evt);
            }
        });

        lbl_frecuencia.setText("Cada cuanto debo ingeir el medicamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_tt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_imagen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_tt2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_nombre)
                            .addGap(18, 18, 18)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_paciente)
                                .addComponent(lbl_hora)
                                .addComponent(lbl_dosis))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_dosis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_horario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_frecuencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_frecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tt)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_tt2)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_dosis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dosis, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_hora)
                            .addComponent(txt_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_paciente)
                            .addComponent(txt_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_frecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_frecuencia))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_imagen)
                    .addComponent(btn_ingresar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_horarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_horarioActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:
        String nombre = txt_nombre.getText().trim();
        String dosis = txt_dosis.getText().trim();
        String horario = txt_horario.getText().trim();
        String paciente = txt_paciente.getText().trim();
        String frecuenciaStr = txt_frecuencia.getText().trim();
        
    if (nombre.isEmpty() || dosis.isEmpty() || horario.isEmpty() || 
            paciente.isEmpty() || frecuenciaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios.");
            return;
        }
    
        int frecuencia ;
        
        try {
            frecuencia = Integer.parseInt(frecuenciaStr);
            if (frecuencia < 1 || frecuencia > 24) {
    JOptionPane.showMessageDialog(this, "La frecuencia debe estar entre 1 y 24 horas");
    return;
    }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La frecuencia debe ser un número entero válido.");
            return;
        } 
        
        insertar_metodo1(nombre, horario, dosis, paciente, rutaImagen, frecuencia);
        
        JOptionPane.showMessageDialog(this, "Medicamento registrado correctamente.");
        limpiarCampos();
        
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imagenActionPerformed

    private void txt_frecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_frecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_frecuenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_medicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_medicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_medicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_medicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_medicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imagen;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel lbl_dosis;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_frecuencia;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_paciente;
    private javax.swing.JLabel lbl_tt;
    private javax.swing.JLabel lbl_tt2;
    private javax.swing.JTextField txt_dosis;
    private javax.swing.JTextField txt_frecuencia;
    private javax.swing.JTextField txt_horario;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_paciente;
    // End of variables declaration//GEN-END:variables
}
